Radar setup
deployed/frontend-radar pull request #1
Opened 2024-07-26 11:58 UTC by justgruba

2024-07-26 18:28 UTC, ViktoriiaKinashDeployed reviewed
looks nice :)

2024-07-26 18:28 UTC, ViktoriiaKinashDeployed commented on src/components/Legend/helper.js
> +    const segment = grouped[element.segment];
maybe we can use just const ring = grouped[element.segment]?.rings[element.ring]; ?

2024-07-26 18:31 UTC, ViktoriiaKinashDeployed approved these changes

2024-08-26 07:52 UTC, KamilPartyka commented on README.md
> +`npm run dev`
Na sam początek ogarnij to readme by miało rączki i nogi 😄

2024-08-26 13:18 UTC, KamilPartyka commented
Wciąż małe te fonty są plus robi się troche misz masz przy mniejszych szerokościach okna np `851`
<img width="894" alt="image" src="https://github.com/user-attachments/assets/07b4c0d7-0458-4ec6-9b6e-7628c2c2a38a">
jak nie masz pomysłu co z tym zrobić to zgarnij Ewelinkę lub Olę by coś doradziły

2024-08-26 13:21 UTC, KamilPartyka commented
Udało mi się wywalić ten radarek bawiąc sie zakładkami front/back
![image](https://github.com/user-attachments/assets/212e9b5e-7b6e-442c-a292-54ed2278ec73)

2024-08-26 13:22 UTC, KamilPartyka commented
Po zmianie karty z backend na front klikanie na nazwy technologi nie pokazują odpowiednich sobie kuleczek na radarku
<img width="774" alt="image" src="https://github.com/user-attachments/assets/a9c1ebf7-0133-4185-b0b0-b93345969f7a">

2024-08-26 13:23 UTC, KamilPartyka commented
Nie numerujmy list od 0 :)
<img width="90" alt="image" src="https://github.com/user-attachments/assets/b52d075e-3c04-43d2-819b-0739f58d1fd9">

2024-08-26 13:24 UTC, KamilPartyka commented
Rzuciłbym jakiś default/informacje o tym że po prostu nie ma technologii z danej "kategorii" albo po prostu nie wyświetlać wtedy nic
<img width="615" alt="Zrzut ekranu 2024-08-26 o 15 23 53" src="https://github.com/user-attachments/assets/acc65768-c09e-417a-994a-893552c4e8b6">

2024-08-26 13:25 UTC, KamilPartyka commented
jakaś faviconka? np ta z deployed
<img width="178" alt="Zrzut ekranu 2024-08-26 o 15 24 58" src="https://github.com/user-attachments/assets/1de17b2e-7de5-4823-993c-c917e7be8d2a">

2024-08-26 13:57 UTC, KamilPartyka commented
> ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot

2024-08-26 14:00 UTC, KamilPartyka commented
Pytanie czysto z ciekawości, nie chciałaś jakiegoś tailwinda użyć tutaj? czysty css to troche meh, chyba ze jest jakiś powód konkretny 😄

2024-08-26 14:02 UTC, KamilPartyka requested changes

2024-08-26 14:02 UTC, KamilPartyka commented on src/context/Context.tsx
> +}) => {
```suggestion
export const TechProvider = ({ children }: { children: ReactNode }) => {
```

https://medium.com/raccoons-group/why-you-probably-shouldnt-use-react-fc-to-type-your-react-components-37ca1243dd13

2024-08-26 14:02 UTC, KamilPartyka commented on src/components/Header/Header.tsx
> +type HeaderProps = {
```suggestion
interface HeaderProps {
```
Moze nie ma to super znaczenia ale do tej pory spotykałem się z preferencją interface nad type w każdym projekcie nad którym dłubałem
https://medium.com/raccoons-group/why-you-probably-shouldnt-use-react-fc-to-type-your-react-components-37ca1243dd13

2024-08-26 14:02 UTC, KamilPartyka commented on src/components/Legend/Element.tsx
> +const Element = ({ element }) => {
where typ? 👀

2024-08-26 14:02 UTC, KamilPartyka commented on src/components/Legend/Legend.tsx
```suggestion
  const groupedDataSegments = Object.keys(groupedData);

```

2024-08-26 14:02 UTC, KamilPartyka commented on src/components/Legend/Legend.tsx
>        {Object.keys(groupedData).map((segmentSlug) => {
```suggestion
      {groupedDataSegments.map((segmentSlug) => {
```

by łatwiej się to czytało ogólnie

2024-08-26 14:02 UTC, KamilPartyka commented on src/components/Legend/Ring.tsx
>          {ring.elements.map((element) => (
jak wyżej 😄

2024-08-26 14:02 UTC, KamilPartyka commented on src/components/Legend/Segment.tsx
>          {Object.keys(segment.rings).map((ringSlug) => {
wrzuć to do consta

2024-08-26 14:02 UTC, KamilPartyka commented on src/components/RadarContent.tsx
> +      <Legend segments={segmentsRight} rings={rings} elements={elements} />
ta legenda może zostać po prawej, tylko style tego grida trzeba dostosować

2024-08-26 14:02 UTC, KamilPartyka commented on src/components/Radar/Radar.jsx
> +const Radar = ({ options, segments, rings, elements }) => {
Zrób go w TS i dodaj typy

2024-08-26 14:02 UTC, KamilPartyka commented on src/context/Context.tsx
> +export const TechProvider: React.FC<{ children: ReactNode }> = ({
Proponuje też z całego tego contextu zrobić hooka i używać go zamiast `useContext(TechContext);`
https://dev.to/alexandprivate/use-react-context-as-a-custom-hook-4ioc

2024-08-26 14:02 UTC, KamilPartyka commented on tsconfig.json
> +  "compilerOptions": {
dożuć tu tez jakiś config prettiera by nie formatował tego każdy kto tu coś będzie robił inaczej według swojego configa lokalnego

2024-08-26 14:06 UTC, KamilPartyka commented
dorzuć też pliczek `.nvmrc` z zawartością `v18.20.4` by bez patrzenia ustawiać node dobrego przy użyciu `nvm use`

2024-08-28 06:26 UTC, justgruba commented on src/components/Radar/Radar.jsx
> +const Radar = ({ options, segments, rings, elements }) => {
Myślę, że przenoszenie tego Radaru do TS pozostawię na czas po Frontowym spotkaniu, teraz poszło na to zdecydowanie za dużo czasu :(

2024-08-28 07:00 UTC, justgruba commented on tsconfig.json
> +  "compilerOptions": {
@KamilPartyka  dorzuć ** https://plorto.pl/jak-sie-pisze/dorzuc-czy-dozuc

2024-08-28 10:13 UTC, KamilPartyka requested changes

2024-08-28 10:13 UTC, KamilPartyka commented on src/components/Legend/Segment.tsx
> +  const ringsKyes = Object.keys(segment.rings);
```suggestion
  const ringsKeys = Object.keys(segment.rings);
```

2024-08-28 10:15 UTC, KamilPartyka commented
W kolejnej wersji dodałbym lepsze skalowanie się strony w zależności od rozmiaru ekranu, na bardzo dużych ekranach te fonty rada i wszytko są ogromne, a na małych wszystko jest ścieśnione

2024-08-28 10:20 UTC, KamilPartyka commented on src/components/Radar/Radar.jsx
> +// TODO: asda
👀

2024-08-28 11:47 UTC, KamilPartyka approved these changes
póki co będzie 😄

2024-08-29 13:04 UTC, merged